apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: einsatzbereit-secrets
spec:
  hostAPI: http://infisical-infisical-standalone-infisical.infisical.svc.cluster.local:8080/api
  resyncInterval: 60
  authentication:
    universalAuth:
      credentialsRef:
        secretName: infisical-machine-identity
        secretNamespace: infisical-operator
      secretsScope:
        projectSlug: homelab-ei-fj
        envSlug: prod
        secretsPath: /ffw-einsatzbereit
  managedSecretReference:
    secretName: einsatzbereit-secrets
    secretNamespace: einsatzbereit
    creationPolicy: Owner
