"""audit log

Revision ID: 0003
Revises: 0002
Create Date: 2026-09-16
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0003"
down_revision: str | None = "0002"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "audit_entries",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("user_name", sa.String(length=120), nullable=False),
        sa.Column("entity_type", sa.String(length=32), nullable=False),
        sa.Column("entity_id", sa.Integer(), nullable=False),
        sa.Column("entity_label", sa.String(length=255), nullable=False),
        sa.Column("member_id", sa.Integer(), nullable=True),
        sa.Column("action", sa.String(length=16), nullable=False),
        sa.Column("changes", sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_audit_entries_at"), "audit_entries", ["at"], unique=False)
    op.create_index(
        op.f("ix_audit_entries_entity_type"), "audit_entries", ["entity_type"], unique=False
    )
    op.create_index(
        op.f("ix_audit_entries_member_id"), "audit_entries", ["member_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_audit_entries_member_id"), table_name="audit_entries")
    op.drop_index(op.f("ix_audit_entries_entity_type"), table_name="audit_entries")
    op.drop_index(op.f("ix_audit_entries_at"), table_name="audit_entries")
    op.drop_table("audit_entries")
    # ### end Alembic commands ###
